kind: Cluster
apiVersion: provisioning.cattle.io/v1
metadata:
  name: mosonline
  namespace: fleet-default
spec:
  rkeConfig:
    machinePools:
      - controlPlaneRole: true
        etcdRole: true
        machineConfigRef:
          apiVersion: elemental.cattle.io/v1beta1
          kind: MachineInventorySelectorTemplate
          name: mosselector
        name: mosmachine
        quantity: 1
        unhealthyNodeTimeout: 0s
        workerRole: true
  kubernetesVersion: v1.23.17+k3s1
