apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: iqemdemomachine2
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
        - name: root
          passwd: admin@123
    elemental:
      install:
        reboot: true
        device: dev/sda
        debug: true
  machineName: iqemdemo2
  machineInventoryLabels:
    location: "europe2"
